config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    devise_for :users,
               path: '', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  devise_scope :doctor do
    devise_for :doctors,
               path: '/doctors', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  authenticated :doctor do
    resources :doctors, controller: 'doctors' do
      resources :time_slot
      resources :doctor_patients
      resources :prescription
      get 'prescription_pdf/:id', to: 'prescription#prescription_pdf', as: 'prescription_pdf'
    end
    root to: 'appointments#index'
  end

  resources :appointments do
    collection do
      scope controller: :appointments do
          get 'doctor_specialty/:specialty_id' => :doctor_specialty, as: 'doctor_specialty'
          get 'availability_slot/:time_slot_id/:appointment_date' => :availability_slot, as: 'availability_slot'
          get 'get_date_range/:appointment_date' => :get_date_range, as: 'get_date_range'
      end
      resources :medical_card do
        resources :medical_history
      end
    end
  end

  authenticated :user do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :users
    resources :doctors
    get 'user_prescriptions/:user_id', to: 'user_prescriptions#index', as: 'user_prescription'
    namespace :admin do
      scope controller: :dashboard do
        get 'users' => :index, as: 'dashboard_users'
        get 'doctors' => :index_doctors , as: 'dashboard_doctors'
      end
      resources :specialties
    end
    root to: 'home#index'
    get '*path' => redirect('/')
  end

  root to: 'home#unregistered'
  get '*path' => redirect('/404')
end

app/models/prescription.rb
class Prescription < ApplicationRecord

  # relaciones
  belongs_to :doctor
  belongs_to :user

  # validaciones
  validates_numericality_of :user_id
  validates_numericality_of :doctor_id
  validates :descripcion, presence: true, length: { in: 5..80 }

  # scopes
  scope :prescription_doctor, ->(doctor) { where(doctor_id: doctor)}
  scope :prescription_user, ->(user) { where(user_id: user)}
  scope :ordenados, -> {order('created_at DESC')}


  def self.joins_prescription
    joins(:doctor).joins(:user)
  end
end

app/controllers/prescription_controller.rb
class PrescriptionController < ApplicationController
  load_and_authorize_resource
  before_action :set_prescription, only: %i[show edit destroy update prescription_pdf]
  before_action :prescription_patients, only: %i[new edit]
  before_action :prescription_params, only: %i[create update]
  before_action :respond_to_html, only: %i[edit new update destroy show]

  def index
    @prescription = Prescription.includes(:user, :doctor).prescription_doctor(current_doctor).ordenados
  end

  def new
    @prescription = Prescription.new
  end

  def show; end

  def edit; end

  def prescription_pdf
    respond_to do |format|
      format.pdf do
        render pdf: 'prescription',
               template: 'prescription/prescription_pdf'
      end
    end
  end

  def create
    @prescription = current_doctor.prescriptions.create(prescription_params)
    respond_to do |format|
      format.js{} if @prescription.save
    end
  end

  def destroy
    respond_to do |format|
      format.js {} if @prescription.destroy
    end
  end

  def update
    respond_to do |format|
      format.js {} if @prescription.update(prescription_params)
    end
  end

  private

  def prescription_patients
    @patients = current_doctor.appointments.ordenados.joins(:user => :medical_card).to_a.uniq(&:user_id)
  end

  def set_prescription
    @prescription = Prescription.find(params[:id])
  end

  def prescription_params
    params.require(:prescription).permit(:user_id, :doctor_id, :descripcion)
  end

  def respond_to_html
    respond_to do |format|
      format.html {
        redirect_to doctor_prescription_index_path,
                    notice: 'error pagina no encontrada'
      }
      format.js {}
    end
  end
end

app/helpers/prescription_helper.rb
module PrescriptionHelper
end

app/views/prescription/_form.html.erb
<div id="prescription-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <legend><%= title %> Prescripcion Médica</legend>
        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">Close</span>
        </button>
      </div>
      <%= form_for(prescription, url: url, remote: true, html: {class:'container'}) do |f| %>
        <div class="form-group">
          <%= f.select :user_id, @patients.collect{ |s| [s.user.username + " " + s.user.last_name + " " + s.user.last_name_mother, s.user.id]},{:prompt => 'Seleccione Usuario'}, {class: 'form-control', required: true}  %>
        </div>
        <hr>
        <div class="form-group">
          <b><%= f.label :prescripcion_medica_paciente, class: 'col-form-label' %>: </b>
            <%= f.text_area :descripcion,rows: 5, autofocus: true, class:'form-control', placeholder: 'Escriba aquí la prescripción médica...',required: true %>
            <small>prescripcion de medicamento ejemplo: (paracetamol c/8 hrs.)</small>
        </div>
        <hr>
        <div class="actions" style="text-align: center">
          <%= f.submit "#{title} Prescripción",class: 'btn btn-sm btn-success' %>
        </div>
      <%end%>
    </div>
  </div>
</div>

app/views/prescription/_prescription.html.erb
<tr id="del_presciption_<%=prescription.id %>" class="text-capitalize">
  <td><%= prescription.user.rut %></td>
  <td><%= prescription.user.username %> <%= prescription.user.last_name%> <%= prescription.user.last_name_mother%></td>
  <td><%= prescription.doctor.username %> <%= prescription.doctor.last_name %> <%= prescription.doctor.last_name_mother %></td>
  <td><%= prescription.descripcion %></td>
  <td><%= prescription.created_at.strftime("%d-%m-%Y") %></td>
  <td style="text-align: center">
    <%= link_to fa_icon("address-book",style: "margin: 5px"), doctor_prescription_path(prescription.doctor.id, prescription.id), remote: true,style: 'color: gray' %>
    <%= link_to fa_icon("trash") ,doctor_prescription_path(prescription.doctor.id, prescription.id), remote: true, method: :delete, style: 'color: red', data: { confirm: 'Desea eliminar?' } %>
    <%= link_to fa_icon("pencil-square-o", style: "margin: 5px"), edit_doctor_prescription_path(prescription.doctor.id, prescription.id), remote: true %>
    <%= link_to fa_icon("file"), doctor_prescription_pdf_path(prescription.doctor.id, prescription.id,format: :pdf), target: "blank" %></td>
  </td>
</tr>

app/views/prescription/_show.html.erb
<div id="medical-history-show" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="container text-right">
        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">Close</span>
        </button>
      </div>
      <div class="container col-md-12 modal-style">
        <div class="card">
          <div class="card-header text-capitalize">
            Paciente <%= @prescription.user.username %> <%= @prescription.user.last_name %> <%= @prescription.user.last_name_mother %>
          </div>
          <div class="card-header text-capitalize">
            Doctor <%= @prescription.doctor.username %> <%= @prescription.doctor.last_name %> <%= @prescription.doctor.last_name_mother %>
          </div>
          <div class="card-body">
            <h5 class="card-title">Prescripción Médica </h5>
            <p class="card-text justify"><%= @prescription.descripcion %></p>
          </div>
          <div class="card-footer text-muted">
            <b> Fecha: </b><%= @prescription.created_at.strftime("%d-%m-%Y")%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prescription/create.js.erb
<% if @prescription.errors.empty? %>
  $("#datatable_description").prepend("<%= j render "prescription/prescription", prescription: @prescription %>")
  $('.alert-success').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Prescripción creada con exito").show();
  $('#prescription-modal').modal('hide');
<% else %>
  alert('<%= @prescription.errors.full_messages[0] %>');
<% end %>

app/views/prescription/destroy.js.erb
$("#del_presciption_<%= @prescription.id %>").remove()
$('.alert-danger').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Prescripción eliminada correctamente").show();

app/views/prescription/edit.js.erb
$('<%= j render "form", prescription: @prescription, url: doctor_prescription_url, title: "Editar" %>').on('hidden.bs.modal', function (e) {
    $(this).remove();
    $('.modal-backdrop').remove();
}).modal();

app/views/prescription/index.html.erb
<%= link_to 'Registrar Nueva Prescripción Médica', new_doctor_prescription_path,remote: true, class: 'mt-3 btn btn-sm btn-success'%>
<h2 class="center">Prescripciones Médicas</h2>
<div class="mt-3 alert alert-success" role="alert" style="display: none;"></div>
<div class="mt-3 alert alert-danger" role="alert" style="display: none;"></div>
<div class="mt-3 card shadow-style table-responsive">
  <div class="card-body">
    <table id="datatable_description" class="table table-hover table-responsive datatable-style-centered">
      <thead>
      <tr style="color: white; background-color: #2979ff">
        <th>Rut Paciente</th>
        <th>Nombre Paciente</th>
        <th>Nombre Medico</th>
        <th>Preescipcion</th>
        <th>Fecha</th>
        <th>Opciones</th>
      </tr>
      </thead>
      <tbody>
      <%= render partial: "prescription/prescription", collection: @prescription %>
      </tbody>
    </table>
  </div>
</div>

app/views/prescription/new.js.erb
$('<%= j render "form",prescription: @prescription, url: doctor_prescription_index_url, title: "Crear" %>').modal();

app/views/prescription/prescription_pdf.pdf.erb
<!doctype html>
<html>
<head>
  <meta charset='utf-8' />
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
</head>
<body>
<div id="content">
  <h3 style="border: 1px solid #ccc;
      color: black;
      text-align: center; border-radius: 4px">Prescripcion Médica</h3>
  <br>
  <br>
    <div class="card">
      <div class="card-header">
      <b> Fecha: </b><%= @prescription.created_at.strftime("%d/%m/%Y")%>
      </div>
      <div class="card-header text-capitalize">
        <b>Rut Paciente :</b> <%= @prescription.user.rut %>
      </div>
      <div class="card-header text-capitalize">
        <b>Paciente :</b> <%= @prescription.user.username %> <%= @prescription.user.last_name %> <%= @prescription.user.last_name_mother %>
      </div>
      <div class="card-header text-capitalize">
        <b>Ciudad :</b> <%= @prescription.user.medical_card.ciudad %>
      </div>
      <div class="card-header text-capitalize">
        <b>Edad :</b> <%= @prescription.user.medical_card.edad %> Años
      </div>
      <div class="card-header text-capitalize">
        <b>Nº Ficha :</b> <%= @prescription.user.medical_card.id %>
      </div>
      <div class="card-header text-capitalize">
        <b>Doctor : </b><%= @prescription.doctor.username %> <%= @prescription.doctor.last_name %> <%= @prescription.doctor.last_name_mother %>
      </div>
      <div class="card-body">
        <h5 class="card-title"><b>Prescripción Médica </b></h5>
        <p class="card-text justify;" style="height: 200px"><%= @prescription.descripcion %></p>
      </div>
    </div>
  <br>
  <br>
  <div style="float: right">
    <h4><%= @prescription.doctor.username %></h4>
    <hr>
    <b>Firma Médico</b>
    </div>
  <div style="float: left">
    <h4><%= @prescription.doctor.username %></h4>
    <hr>
    <b>Timbre Institución</b>
  </div>
</div>
</body>
</html>

app/views/prescription/show.js.erb
$('<%= j render "show" %>').modal();

app/views/prescription/update.js.erb
<% if @prescription.errors.empty? %>
$('#del_presciption_<%= @prescription.id %>').replaceWith(' <%= j render "prescription/prescription", prescription: @prescription %>');
$('.alert-success').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Prescripción Médica modificada con exito").show();
$('#prescription-modal').modal('hide');
<% else %>
alert('<%= @prescription.errors.full_messages[0] %>');
<% end %>