config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    devise_for :users,
               path: '', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  devise_scope :doctor do
    devise_for :doctors,
               path: '/doctors', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  authenticated :doctor do
    resources :doctors, controller: 'doctors' do
      resources :time_slot
      resources :doctor_patients
      resources :prescription
      get 'prescription_pdf/:id', to: 'prescription#prescription_pdf', as: 'prescription_pdf'
    end
    root to: 'appointments#index'
  end

  resources :appointments do
    collection do
      scope controller: :appointments do
          get 'doctor_specialty/:specialty_id' => :doctor_specialty, as: 'doctor_specialty'
          get 'availability_slot/:time_slot_id/:appointment_date' => :availability_slot, as: 'availability_slot'
          get 'get_date_range/:appointment_date' => :get_date_range, as: 'get_date_range'
      end
      resources :medical_card do
        resources :medical_history
      end
    end
  end

  authenticated :user do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :users
    resources :doctors
    get 'user_prescriptions/:user_id', to: 'user_prescriptions#index', as: 'user_prescription'
    namespace :admin do
      scope controller: :dashboard do
        get 'users' => :index, as: 'dashboard_users'
        get 'doctors' => :index_doctors , as: 'dashboard_doctors'
      end
      resources :specialties
    end
    root to: 'home#index'
    get '*path' => redirect('/')
  end

  root to: 'home#unregistered'
  get '*path' => redirect('/404')
end

app/views/partials/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="footer-block center mt-2">This work is licensed under the GPL v2 License <span class="copyleft">&copy;</span> <%= Date.today.year %>.</p>
  </div>
</div>

app/views/partials/_nav.html.erb
<header class="navbar navbar-expand-lg navbar-custom fixed-top nav-shadow">
  <a class="navbar-brand" style="color: white" href="/">Sistema Médico</a>

  <button class="navbar-toggler" style="background-color: white" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-md-auto d-md-flex">
      <%= doctor_links %>
      <% if user_signed_in? or doctor_signed_in? %>
        <%= usertype_helper%>
        <%=  user_links %>
        <% if user_signed_in? %>
        <li class="nav-item">
          <a class="navbar-brand" href="<%= edit_user_path(current_user) %>" data-remote="true"><%= image_tag(current_user.avatar.url, class:"img_nav_profile") %>
            <span class="username-span"><%= current_user.username %> <%= current_user.last_name %></span> <i style="color: white" class="fa fa-pencil-square-o"></i></a>
        </li>
          <% elsif doctor_signed_in? %>
          <li class="nav-item">
            <a class="navbar-brand" href="<%= edit_doctor_path(current_doctor) %>" data-remote="true"><%= image_tag(current_doctor.avatar.url, class:"img_nav_profile") %>
              <span class="username-span"><%= current_doctor.username %> <%= current_doctor.last_name %></span> <i style="color: white" class="fa fa-pencil-square-o"></i></a>
          </li>
        <%end%>
        <li class="nav-item">
          <a class="nav-link" data-method="delete" href="<%= destroy_user_session_path %>">Salir <i class="fa fa-sign-out"></i></a>
        </li>
      <% else %>
        <li class="nav-item">
          <a class="nav-link"  href="<%= new_user_session_path %>">Ingreso Usuarios <i class="fa fa-sign-in"></i></a>
        </li>
        <li class="nav-item">
          <a class="nav-link"  href="<%= new_doctor_session_path %>">Ingreso Médicos <i class="fa fa-sign-in"></i></a>
        </li>
      <%end%>
    </ul>
  </div>
</header>