config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    devise_for :users,
               path: '', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  devise_scope :doctor do
    devise_for :doctors,
               path: '/doctors', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  authenticated :doctor do
    resources :doctors, controller: 'doctors' do
      resources :time_slot
      resources :doctor_patients
      resources :prescription
      get 'prescription_pdf/:id', to: 'prescription#prescription_pdf', as: 'prescription_pdf'
    end
    root to: 'appointments#index'
  end

  resources :appointments do
    collection do
      scope controller: :appointments do
          get 'doctor_specialty/:specialty_id' => :doctor_specialty, as: 'doctor_specialty'
          get 'availability_slot/:time_slot_id/:appointment_date' => :availability_slot, as: 'availability_slot'
          get 'get_date_range/:appointment_date' => :get_date_range, as: 'get_date_range'
      end
      resources :medical_card do
        resources :medical_history
      end
    end
  end

  authenticated :user do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :users
    resources :doctors
    get 'user_prescriptions/:user_id', to: 'user_prescriptions#index', as: 'user_prescription'
    namespace :admin do
      scope controller: :dashboard do
        get 'users' => :index, as: 'dashboard_users'
        get 'doctors' => :index_doctors , as: 'dashboard_doctors'
      end
      resources :specialties
    end
    root to: 'home#index'
    get '*path' => redirect('/')
  end

  root to: 'home#unregistered'
  get '*path' => redirect('/404')
end

app/models/medical_card.rb
class MedicalCard < ApplicationRecord
  belongs_to :user

  has_many :medical_histories, dependent: :destroy
  has_many :doctors, through: :medical_histories

  validates :diagnostico_user, presence: true, length: { in: 5..20 },
            format: { with: /\A[a-zA-Z ]+\z/, message: 'Solo letras' }

  validates :ciudad, presence: true, length: { in: 2..20 },
            format: { with: /\A[a-zA-Z ]+\z/, message: 'Solo letras' }

  validates :edad, presence: true, numericality: true, length: { in: 1..3 }
  validates :peso, presence: true, numericality: true
  validates :estatura, presence: true, numericality: true

  validates :alergia, presence: true, length: { in: 2..20 },
            format: { with: /\A[a-zA-Z ]+\z/, message: 'Solo letras' }

end

app/controllers/medical_card_controller.rb
class MedicalCardController < ApplicationController
  load_and_authorize_resource param_method: :medical_params
  before_action :set_medical, only: %i[edit update destroy show]
  before_action :respond_to_html, only: %i[edit destroy create]

  def show
    @medical_history = MedicalHistory.where(medical_card_id: @medical_card).ordenados
  end

  def new
   @medical_card = MedicalCard.new
  end

  def create
    @medical_card = MedicalCard.new(medical_params)
    if @medical_card.save
      respond_to do |format|
        format.js {}
      end
    end
  end

  def edit; end

  def update
    if @medical_card.update(medical_params)
      respond_to do |format|
        format.js {}
      end
    end
  end

  private

  def set_medical
    @medical_card = MedicalCard.find(params[:id])
  end

  def medical_params
    params.require(:medical_card).permit(:diagnostico_user, :ciudad, :edad, :peso, :estatura, :alergia, :user_id)
  end

  def respond_to_html
    respond_to do |format|
      format.html { redirect_to appointments_path, notice: 'error pagina no encontrada' }
      format.js {}
    end
  end
end

app/helpers/medical_card_helper.rb
module MedicalCardHelper
end

app/views/medical_card/_form.html.erb
<div id="medical-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <legend><%= title %> Ficha Médica</legend>
        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">Close</span>
        </button>
      </div>
        <%= form_for(medical_card, url: url, remote: true, html: {class:'container col-md-10'}) do |f| %>
          <div class="form-group row">
            <%= f.label :diagnostico_paciente, class: 'col-6 col-form-label' %>
            <div class="col-6">
              <%= f.text_field :diagnostico_user, autofocus: true, class:'form-control', required: true %>
              <small>breve diagnostico ejemplo: (cefalea constante)</small>
            </div>
          </div>
        <hr>
          <div class="form-group row">
            <%= f.label :ciudad, class: 'col-4 col-form-label' %>
            <div class="col-8">
              <%= f.text_field :ciudad, autofocus: true, class:'form-control', required: true %>
            </div>
          </div>
        <hr>
          <div class="form-group row">
            <%= f.label :edad_paciente, class: 'col-6 col-form-label' %>
            <div class="col-3">
              <%= f.number_field :edad, autofocus: true, class:'form-control', required: true %>
            </div>
            <div class="col-1">años</div>
          </div>
        <hr>
          <div class="form-group row">
            <%= f.label :peso_paciente, class: 'col-6 col-form-label' %>
            <div class="col-3">
              <%= f.number_field :peso, autofocus: true, class:'form-control', required: true, step: :any %>
            </div>
            <div class="col-1">Kg</div>
          </div>
        <hr>
          <div class="form-group row">
            <%= f.label :estatura_paciente, class: 'col-6 col-form-label' %>
            <div class="col-3">
              <%= f.number_field :estatura, autofocus: true, class:'form-control', required: true, step: :any %>
            </div>
            <div class="col-1">Cm</div>
          </div>
        <hr>
          <div class="form-group row">
            <%= f.label :alergia_paciente, class: 'col-5 col-form-label' %>
            <div class="col-7">
              <%= f.text_field :alergia, autofocus: true, class:'form-control', required: true %>
              <small>especifique si paciente presenta alergia en breves palabras</small>
            </div>
          </div>
            <% unless controller.action_name.eql?("edit") %>
            <%= f.hidden_field :user_id, :value => params[:user_id] %>
              <%end%>
            <div class="actions" style="text-align: center">
              <%= f.submit "#{title} ficha",class: 'btn btn-sm btn-success' %>
            </div>
        <%end%>
    </div>
  </div>
</div>

app/views/medical_card/create.js.erb
<% if @medical_card.errors.empty? %>
$('.alert-success').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Ficha creada con exito").show();
$('#user_mc_<%= @medical_card.user_id %>').replaceWith("<td style='text-align: center'><a style='color: gray' href='<%= medical_card_path(@medical_card.id) %>'><i style='margin: 5px' class='fa fa-address-book'></i></a><a data-remote='true' href='<%= edit_medical_card_path(@medical_card.id) %>'><i style='margin: 5px' class='fa fa-pencil-square-o'></i></a></td>");
$('#medical-modal').modal('hide');
<% else %>
alert('<%= @medical_card.errors.full_messages[0] %>');
<% end %>

app/views/medical_card/edit.js.erb
$('<%= j render "form", medical_card: @medical_card, url: medical_card_url, title: "Edit" %>').on('hidden.bs.modal', function (e) {
    $(this).remove();
    $('.modal-backdrop').remove();
}).modal();

app/views/medical_card/new.js.erb
$('<%= j render "form",medical_card: @medical_card, url: medical_card_index_url, title: "Create" %>').modal();

app/views/medical_card/show.html.erb
<div class="mt-3 alert alert-success" role="alert" style="display: none;"></div>
<div class="mt-3 alert alert-danger" role="alert" style="display: none;"></div>
<div class="container">
<div class="card text-center mt-4 shadow-style" style="width: 20rem; display: inline-block; float: left">
    <div class="card-header text-white bg-primary text-capitalize">
      Ficha Médica <%= @medical_card.user.username %> <%= @medical_card.user.last_name %> <%= @medical_card.user.last_name_mother %>
    </div>
    <ul class="list-group list-group-flush text-capitalize">
      <li class="list-group-item"><h6>Diagnostico: <%= @medical_card.diagnostico_user %></h6></li>
      <li class="list-group-item"><h6>Ciudad: <%= @medical_card.ciudad %></h6></li>
      <li class="list-group-item"><h6>Edad: <%= @medical_card.edad %> Años</h6></li>
      <li class="list-group-item"><h6>Peso: <%= @medical_card.peso %> Kg</h6></li>
      <li class="list-group-item"><h6>Estatura: <%= @medical_card.estatura %> Cm</h6></li>
      <li class="list-group-item"><h6>Alergia: <%= @medical_card.alergia %></h6></li>
    </ul>
  <%= link_to "volver atras", appointments_path,class: "btn btn-sm btn-primary mt-2 mb-2" %>
</div>
<div class="mt-4 card shadow-style text-capitalize" style="float: right">
  <div class="card-body">
    <span style="margin: auto;display: table"><%= link_to "Crear Nueva Observación", new_medical_card_medical_history_path(medical_card_id: @medical_card.id), remote: true, class: "btn btn-sm btn-primary mb-2"%></span>
    <div class="card-header mb-2 center">Historial Médico <%= @medical_card.user.username %> <%= @medical_card.user.last_name %> <%= @medical_card.user.last_name_mother %></div>
      <table id="datatable_historial" class="table table-hover table-responsive" style="border-radius: 4px">
        <thead>
        <tr style="color: white; background-color: #2979ff;">
          <th>Nombre Médico</th>
          <th>Observación</th>
          <th>Fecha</th>
          <th>Opciones</th>
        </tr>
        </thead>
        <tbody>
        <%= render partial: "medical_history/medical_history", collection: @medical_history %>
        </tbody>
      </table>
  </div>
</div>
</div>

app/views/medical_card/update.js.erb
<% if @medical_card.errors.empty? %>
$('.alert-success').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Ficha medica modificada con exito").show();
$('#medical-modal').modal('hide');
<% else %>
alert('<%= @medical_card.errors.full_messages[0] %>');
<% end %>