config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    devise_for :users,
               path: '', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  devise_scope :doctor do
    devise_for :doctors,
               path: '/doctors', path_names: {
                 sign_in: 'sign_in',
                 sign_out: 'logout'
               }
  end

  authenticated :doctor do
    resources :doctors, controller: 'doctors' do
      resources :time_slot
      resources :doctor_patients
      resources :prescription
      get 'prescription_pdf/:id', to: 'prescription#prescription_pdf', as: 'prescription_pdf'
    end
    root to: 'appointments#index'
  end

  resources :appointments do
    collection do
      scope controller: :appointments do
          get 'doctor_specialty/:specialty_id' => :doctor_specialty, as: 'doctor_specialty'
          get 'availability_slot/:time_slot_id/:appointment_date' => :availability_slot, as: 'availability_slot'
          get 'get_date_range/:appointment_date' => :get_date_range, as: 'get_date_range'
      end
      resources :medical_card do
        resources :medical_history
      end
    end
  end

  authenticated :user do
    # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :users
    resources :doctors
    get 'user_prescriptions/:user_id', to: 'user_prescriptions#index', as: 'user_prescription'
    namespace :admin do
      scope controller: :dashboard do
        get 'users' => :index, as: 'dashboard_users'
        get 'doctors' => :index_doctors , as: 'dashboard_doctors'
      end
      resources :specialties
    end
    root to: 'home#index'
    get '*path' => redirect('/')
  end

  root to: 'home#unregistered'
  get '*path' => redirect('/404')
end

app/models/medical_history.rb
class MedicalHistory < ApplicationRecord
  belongs_to :medical_card
  belongs_to :doctor

  scope :ordenados, -> { order('created_at desc') }
  validates :body, presence: true, length: { in: 10..250 }
end

app/controllers/medical_history_controller.rb
class MedicalHistoryController < ApplicationController
  before_action :set_medical_history, only: %i[edit update show destroy]
  before_action :respond_to_html, only: %i[edit new update destroy show]
  load_and_authorize_resource

  def show; end

  def edit; end

  def new
    @medical_history = MedicalHistory.new
  end

  def update
    respond_to do |format|
      format.js {} if @medical_history.update(medical_history_params)
    end
  end

  def create
    @medical_history = current_doctor.medical_histories.create(medical_history_params)
    respond_to do |format|
      format.js {} if @medical_history.save
    end
  end

  def destroy
    if @medical_history.destroy
      respond_to do |format|
        format.js {}
      end
    end
  end

  def set_medical_history
    @medical_history = MedicalHistory.find(params[:id])
  end

  def medical_history_params
    params.require(:medical_history).permit(:body, :medical_card_id)
  end

  def respond_to_html
    respond_to do |format|
      format.html { redirect_to appointments_path, notice: 'error pagina no encontrada' }
      format.js {}
    end
  end
end

app/views/medical_history/_form.html.erb
<div id="medical-history-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title right"><%= title %> Historial Médico</h4>
        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">Close</span>
        </button>
      </div>
        <%= form_for(medical_history, url: url, remote: true, html: {class:'container col-md-10'}) do |f| %>
            <div class="form-group">
              <%= f.label :observacion_paciente, class: 'col-8 col-form-label' %>
              <%= f.text_area :body, rows: 10,autofocus: true, placeholder: 'Escriba aquí la observación..' ,class:'form-control', required: true %>
            </div>
            <hr>
            <% if controller.action_name.eql?("new") %>
              <%= f.hidden_field :medical_card_id, :value => params[:medical_card_id] %>
            <%end%>
            <div class="actions" style="text-align: center">
              <%= f.submit "#{title} observacion",class: 'btn btn-sm btn-success' %>
            </div>
        <%end%>
    </div>
  </div>
</div>

app/views/medical_history/_medical_history.html.erb
<tr id="medical_history_<%=medical_history.id%>">
  <td> <%= medical_history.doctor.username %></td>
  <td><%= sanitize medical_history.body[0..30].capitalize, tags: %w(strong em a p b), attributes: %w(href) %>...</td>
  <td><%= medical_history.created_at.strftime("%d-%m-%Y") %></td>
  <td style="text-align: center"><%= link_to fa_icon("address-book",style: "margin: 5px"), medical_card_medical_history_path(medical_history.medical_card_id, medical_history), remote: true, style: 'color: gray' %>
    <%= link_to fa_icon("pencil-square-o", style: "margin: 5px"), edit_medical_card_medical_history_path(medical_history.medical_card_id, medical_history), remote: true %>
  <% if current_doctor.id.eql?(medical_history.doctor_id) %>
      <%= link_to fa_icon("trash") ,medical_card_medical_history_path(medical_history.medical_card_id, medical_history), remote: true, method: :delete, style: 'color: red', data: { confirm: 'Desea eliminar?' } %>
  <% end %>
  </td>
</tr>

app/views/medical_history/_show.html.erb
<div id="medical-history-show" class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="container text-right">
        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">Close</span>
        </button>
      </div>
      <div class="container col-md-12 modal-style">
        <div class="card">
          <div class="card-header text-capitalize">
            Paciente <%= @medical_history.medical_card.user.username %> <%= @medical_history.medical_card.user.last_name %> <%= @medical_history.medical_card.user.last_name_mother %>
          </div>
          <div class="card-header text-capitalize">
            Doctor <%= @medical_history.doctor.username %> <%= @medical_history.doctor.last_name %> <%= @medical_history.doctor.last_name_mother %>
          </div>
          <div class="card-body">
            <h5 class="card-title">Observación </h5>
            <p class="card-text justify"><%= @medical_history.body %></p>
          </div>
          <div class="card-footer text-muted">
            <b> Fecha: </b><%= @medical_history.created_at.strftime("%d-%m-%Y")%>
          </div>
        </div>
          </div>
      </div>
    </div>
  </div>

app/views/medical_history/create.js.erb
<% if @medical_history.errors.empty? %>
$("#datatable_historial").prepend("<%= j render "medical_history/medical_history", medical_history: @medical_history %>")
$('.alert-success').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Observación creada con exito").show();
$('#medical-history-modal').modal('hide');
<% else %>
alert('<%= @medical_history.errors.full_messages[0] %>');
<% end %>

app/views/medical_history/destroy.js.erb
$("#medical_history_<%= @medical_history.id %>").remove()
$('.alert-danger').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Historial eliminado correctamente").show();

app/views/medical_history/edit.js.erb
$('<%= j render "form", medical_history: @medical_history, url: medical_card_medical_history_url, title: "Edit" %>').on('hidden.bs.modal', function (e) {
    $(this).remove();
    $('.modal-backdrop').remove();
}).modal();

app/views/medical_history/new.js.erb
$('<%= j render "form",medical_history: @medical_history, url: medical_card_medical_history_index_url, title: "Crear" %>').modal();

app/views/medical_history/show.js.erb
$('<%= j render "show", title: "Observación" %>').modal();

app/views/medical_history/update.js.erb
<% if @medical_history.errors.empty? %>
$('#medical_history_<%= @medical_history.id %>').replaceWith(' <%= j render "medical_history/medical_history", medical_history: @medical_history %>');
$('.alert-success').html("<a href='#' class='close' data-dismiss='alert' aria-label='close'>&times;</a><strong>Success</strong> Observación modificada con exito").show();
$('#medical-history-modal').modal('hide');
<% else %>
alert('<%= @medical_history.errors.full_messages[0] %>');
<% end %>